// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ELoa5IywqYPZTBZqY_Y6nIbrI4IKV_E',
    appId: '1:811360459131:web:05c0699a551a6c13f745de',
    messagingSenderId: '811360459131',
    projectId: 'webrtc-9e2cc',
    authDomain: 'webrtc-9e2cc.firebaseapp.com',
    storageBucket: 'webrtc-9e2cc.appspot.com',
    measurementId: 'G-9GS6190EZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIV2LZ9WkgcyIfSh3WhXHEN0856G_J5X0',
    appId: '1:811360459131:android:bd53dc58d286def9f745de',
    messagingSenderId: '811360459131',
    projectId: 'webrtc-9e2cc',
    storageBucket: 'webrtc-9e2cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8wChJZfmI_4h6ir2fAhM5RuuqZ887-s',
    appId: '1:811360459131:ios:c4120ac4715a0102f745de',
    messagingSenderId: '811360459131',
    projectId: 'webrtc-9e2cc',
    storageBucket: 'webrtc-9e2cc.appspot.com',
    iosBundleId: 'com.example.deovibase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8wChJZfmI_4h6ir2fAhM5RuuqZ887-s',
    appId: '1:811360459131:ios:c4120ac4715a0102f745de',
    messagingSenderId: '811360459131',
    projectId: 'webrtc-9e2cc',
    storageBucket: 'webrtc-9e2cc.appspot.com',
    iosBundleId: 'com.example.deovibase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ELoa5IywqYPZTBZqY_Y6nIbrI4IKV_E',
    appId: '1:811360459131:web:5172023e32535d24f745de',
    messagingSenderId: '811360459131',
    projectId: 'webrtc-9e2cc',
    authDomain: 'webrtc-9e2cc.firebaseapp.com',
    storageBucket: 'webrtc-9e2cc.appspot.com',
    measurementId: 'G-NKD4KLNBY1',
  );
}
